[package]
name = "mclib"
version.workspace = true
edition.workspace = true

[dependencies]
sharingan = {workspace = true}

atomig = {workspace = true, features = ["derive"]}
md5 = {workspace = true}
hex = {workspace = true}
optfield = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
sha1 = {workspace = true}
smart-default = {workspace = true}
uuid = {workspace = true}

regex = "1"
shlex = "1"
sysinfo = "0.31.4"
zip = { version = "2.4", default-features = false, features = ["deflate"] }

tempfile = "3"
